### ISSUE TITLE
common.apex.runtime.impl.ExecutionException

### ISSUE THREAD

**Issue by vsmarimuthu** [PropicSignifi/Query.apex#57]
I Am using one query like this
`
List<Case> oList= new DMLOperationsHandler('Case').                            selectFields('Id,CaseNumber,ReceivedDate__c,CreatedDate,Owner.FirstName,Owner.Lastname,Origin').                                                       
                            run();  
`
and getting error as 

`common.apex.runtime.impl.ExecutionException: Cannot find firstname in object Group
`

Can you please correct me if I do anything wrong?

**Comment by HenryRLee** [comment]
Hi, I think you could select `Owner.Name` instead of `Owner.FirstName`. Because `OwnerId` is a polymorphic lookup, which can be a user Id or a group Id. So I guess you cannot select `FirstName` in this case.

**Comment by vsmarimuthu** [comment]
Actually when I write like this , I am not getting any Issues.

List<Case> oCase=[select Id,CaseNumber,ReceivedDate__c,CreatedDate,Owner.FirstName,Owner.Lastname,Origin from Case];


So do we have to follow the Owner.Name only as per your suggestion?

**Comment by HenryRLee** [comment]
I see the issue you're facing. I just did an update to fix this issue. You may pull the latest code and try again.

**Comment by aranwe** [comment]
Just curious, what was the issue?:)

**Comment by HenryRLee** [comment]
Hi @aranwe 
In the very early implementation, we enforced field-level security, by traversing all the fields selected, including the fields from the parent object. In order to traverse the fields in the parent object, we had to get the object type of the parent object. If the parent field is a polymorphic lookup, I just randomly chose one, assuming that we could only select the common fields of the polymorphic object types. But when this issue was raised, I realized that assumption wasn't always true (`FirstName` is not a common field but it can be selected in native SOQL).

Since APEX version 48, we can use the `WITH SECURITY_ENFORCED` to enforce security checks, instead of traversing all the fields. Therefore I just replaced all the security checking codes with the new `WITH SECURITY_ENFORCED` keyword. You may find it in this commit f5b2b7c65e.

**Comment by aranwe** [comment]
Ah, that makes sense, thank you:)

**Comment by vsmarimuthu** [comment]
@HenryRLee  
Things are looking good now. 
Thank you for your support.
